
create table employeepayroll(ID int AUTO_INCREMENT PRIMARY KEY,NAME varchar(20),SALARY INT(20),STARTDATE date NOT NULL);
INSERT INTO employeepayroll(NAME,SALARY,STARTDATE) VALUES('SAM',20000,'2022-03-10') WHERE ID = 1;
INSERT INTO employeepayroll(NAME,SALARY,STARTDATE) VALUES('VISHAL',27000,'2021-10-01');
INSERT INTO employeepayroll(NAME,SALARY,STARTDATE) VALUES('SARAVANAN',70000,'2017-06-06');
SELECT * FROM employeepayroll;
select * from employeepayroll where NAME='VISHAL';
SELECT * FROM employeepayroll WHERE STARTDATE BETWEEN CAST('2018-01-01' AS DATE) AND DATE(NOW());
ALTER TABLE employeepayroll ADD GENDER VARCHAR(10) AFTER NAME;
UPDATE employeepayroll SET NAME='SHALINI' WHERE ID=3;
SELECT gender as GEN,SUM(salary) AS TOTAL,ROUND(avg(SALARY),2) AS AVERAGE,min(SALARY) AS LOW,max(SALARY) AS HIGH,count(gender) AS members FROM employeepayroll WHERE gender = 'M' OR GENDER='F'  GROUP BY gender;
ALTER TABLE employeepayroll ADD (PHONENO INT NOT NULL,ADDRESS VARCHAR(40) NOT NULL,DEPARTMENT VARCHAR(10) NOT NULL);
INSERT INTO employeepayroll(PHONENO,ADDRESS,DEPARTMENT) values(7436436,'3,katur','production');
INSERT INTO employeepayroll(PHONENO,ADDRESS,DEPARTMENT) values(4673653,'67,MALAVAKAM','R&D');
INSERT INTO employeepayroll(PHONENO,ADDRESS,DEPARTMENT) values(9867583,'5,CHENNAI','HR');
ALTER TABLE employeepayroll ADD (BASICPAY FLOAT(20) NOT NULL,DETACTION FLOAT(20) NOT NULL,TAXABLE_PAY FLOAT(20) NOT NULL,INCOMETAX FLOAT(10) NOT NULL,NETPAY FLOAT(20) NOT NULL);
INSERT INTO employeepayroll(BASICPAY,DETACTION,TAXABLE_PAY,INCOMETAX,NETPAY) values(15000,10000,2000,1000,5000),(17000,13000,2300,1060,4600),(19000,1000,200,100,6000);